[package]
name = "color_vlc"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "decoder"
path = "src/decoder_main.rs"

# 第二个二进制文件
[[bin]]
name = "encoder"
path = "src/encoder_main.rs"

[[bin]]
name = "yolo_test"
path = "src/yolo_test.rs"

[[bin]]
name = "gen_base"
path = "src/gen_base.rs"

[[bin]]
name = "qrcode_test"
path = "src/qrcode_test.rs"

[[bin]]
name = "gen_ideal"
path = "src/gen_ideal.rs"

[dependencies]
ndarray = "0.17.2"
video-rs = { version = "0.10.5", features = ["ndarray"] }
ffmpeg-next = "7.1"
opencv = { version = "0.98.1", features = ["clang-runtime", "dnn_superres"] }
image = "0.25.1"
const_format = "0.2.35"
anyhow = "1.0.102"
reed-solomon = "0.2.1"
rand = "0.10.0"
g2p = "1.2.2"
lru = "0.16.3"
palette = "0.7.6"
ort = { version = "2.0.0-rc.12", features = ["cuda"] }


[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = 0
strip = "symbols"
incremental = false


[profile.release.package."*"]
opt-level = 3
